---
title: "explaratory_data_analysis"
author: "saahityae"
date: "25 September 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir="~/Desktop/5th-SEM-Stuff/DataAnalytics/DataAnalyticsProject/")
```

```{r}
library(tidyverse)
```
```{r}
vehicle_data <- read.csv("../DataAnalyticsProject/data/Vehicle_Information.csv.bz2")
```

```{r}
summary(vehicle_data)
```

```{r}
library(hexbin)
```

```{r}
list.files("data/")
```
```{r}
#system.time(accident_data <- read.csv("data/Accident_Information.csv.bz2"))
#system.time(Vehicle_data <- read.csv("data//Vehicle_Information.csv.bz2"))
```

```{r}
summary(Vehicle_data)
```

```{r}
ggplot(accident_data, aes(x = Time)) + geom_bar(stat = "count") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
str(accident_data)
```
```{r}
summary(accident_data)
```

```{r}
sapply(accident_data, class)
```

```{r}
ggplot(data = accident_data, mapping=aes(x=Number_of_Casualties))+geom_histogram(binwidth = 1)
boxplot(accident_data$Number_of_Casualties) #even the 2's are being considered as outliers, Why is 1 the most common value
count(accident_data, Number_of_Casualties == 1)
```
Series of Accident data variations across Years, etc
```{r}
ggplot(data = accident_data, mapping = aes(x = Year, color = Accident_Severity))+geom_freqpoly(binwidth=1)
```

```{r}
ggplot(data = accident_data, mapping = aes(x=Year, color=Junction_Detail))+geom_freqpoly(binwidth=1)
#not at junction or within 20 metres has shown atleast 25% fall
```

```{r}
ggplot(data = accident_data, mapping = aes(x = Year, color = Urban_or_Rural_Area))+geom_freqpoly(binwidth=1)
```

```{r}
ggplot(data = accident_data, mapping = aes(x = Year, color = Road_Type))+geom_freqpoly(binwidth=1)
```

```{r}
ggplot(data = accident_data, mapping = aes(x = Year, color = Weather_Conditions))+geom_freqpoly(binwidth=1)
```

```{r}
ggplot(data = accident_data%>%filter(Weather_Conditions != "Data missing or out of range"), mapping = aes(x = Year, y = ..density.. ,fill = Weather_Conditions))+
  geom_density(alpha = 0.4)

  #geom_freqpoly(binwidth=1)
```

```{r}

```

```{r}
ggplot(data = accident_data, mapping = aes(x = Year, color = Road_Surface_Conditions))+geom_freqpoly(binwidth=1)
```

```{r}
ggplot(data = accident_data, mapping = aes(x = Year, fill = Road_Surface_Conditions, y = ..density.. ))+
    geom_density(alpha = 0.4)

  #geom_freqpoly(binwidth=1)

```

```{r}
ggplot(data = accident_data, mapping = aes(x = Year, color = Day_of_Week))+
  geom_freqpoly(binwidth=1)
```

```{r}
ggplot(data = accident_data, mapping = aes(x = Year, color = Junction_Control))+geom_freqpoly(binwidth=1)+
  labs(title = "Accidents over the Years based on Junction Control")
```

```{r}
ggplot(accident_data, aes(x=Latitude))+geom_histogram()+labs(title="Accidents by latitude") #lattitude of london is 51.5
```

```{r}
#ggplot(accident_data, aes(x=Local_Authority_.District.))+geom_bar()  #bad viz
#group_by(accident_data, Local_Authority_.District.) %>%
  #summarise(n = n()) %>% arrange(n)
```

```{r}
group_by(accident_data, Local_Authority_.Highway.) %>%
  summarise(n = n()) %>% arrange(n)
```

```{r}
ggplot(data = accident_data) +
  geom_count(mapping = aes(x = Local_Authority_.District., y = Local_Authority_.Highway.))
accident_data %>% filter(Local_Authority_.District. != Local_Authority_.Highway.) %>% nrow()
```

```{r}

ggplot(data = accident_data[accident_data$Carriageway_Hazards != 'None', ]) +
  geom_count(mapping = aes(x = Accident_Severity, y = Carriageway_Hazards)) +
  labs(title = "Carriage Hazards vs Accident Severity")

```

```{r}
ggplot(data = accident_data[accident_data$Accident_Severity != 'Slight', ]) +
  geom_count(mapping = aes(x = Accident_Severity, y = Day_of_Week,color = Day_of_Week)) +
  labs(title = "Day of Week vs Accident Severity")
```

```{r}
ggplot(data = accident_data[accident_data$Carriageway_Hazards != 'None', ]) +
  geom_count(mapping = aes(x = Accident_Severity, y = Road_Surface_Conditions)) +
  labs(title = "Road Surface vs Severity")
```

```{r}

ggplot(data = accident_data[accident_data$Light_Conditions != 'Darkness - lighting unknown', ]) +
  geom_point(mapping = aes(x = Latitude, y = Longitude, color = Light_Conditions), alpha = 0.01) + guides(colour = guide_legend(override.aes = list(alpha = 1)))

```

```{r}
ggplot(data = accident_data) +
  geom_point(mapping = aes(x = X1st_Road_Number, y = X2nd_Road_Number), alpha = 0.007)
```

```{r}
library(leaflet)
```

```{r}
m = leaflet() %>% addTiles() 
m %>% addPolygons(lng = contrib.pc.find.dt$lng[1:5243] , lat = contrib.pc.find.dt$lat[1:5243] , fillColor = "blue" , color = "black", weight = 1)
```
