---
title: "Untitled"
output: pdf_document
---

```{r}
library(tidyverse)
library(ggmap)
library(DataExplorer)
library(MASS)
library(gridExtra)
library(ggtern)
library(leaflet)
library(mice)
library(data.table)
library(sp)
library(RCurl)
library(RJSONIO)
library(KernSmooth)
library(lubridate)
```

```{r}
dacc <- read_csv("Accident_Information.csv")
dveh <- read_csv("Vehicle_Information.csv")

accident_data <- dacc
vehicle_data <- dveh
district = NULL

```



```{r}

accident_data <- drop_na(accident_data, Latitude)
accident_data <- drop_na(accident_data, Longitude)
names(accident_data)[15] = "Local_Authority_.District."
names(accident_data)[16] = "Local_Authority_.Highway."

  accident_data$Accident_Severity = factor(accident_data$Accident_Severity,order = TRUE,levels = c("Slight","Serious","Fatal"))
  accident_data[["1st_Road_Class"]] = factor(accident_data[["1st_Road_Class"]])
  accident_data$Light_Conditions = factor(accident_data$Light_Conditions)
  accident_data[["Local_Authority_.District."]] = factor(accident_data[["Local_Authority_.District."]])
  accident_data$Day_of_Week = factor(accident_data$Day_of_Week)
  accident_data$Urban_or_Rural_Area = factor(accident_data$Urban_or_Rural_Area)
  accident_data$Weather_Conditions = factor(accident_data$Weather_Conditions)
  accident_data$Junction_Control = factor(accident_data$Junction_Control)
  accident_data$Road_Surface_Conditions = factor(accident_data$Road_Surface_Conditions)
  accident_data$Road_Type = factor(accident_data$Road_Type)
  accident_data$InScotland = factor(accident_data$InScotland)
  accident_data$Carriageway_Hazards = factor(accident_data$Carriageway_Hazards)
  accident_data[["2nd_Road_Class"]] = factor(accident_data[["2nd_Road_Class"]])
  accident_data$Special_Conditions_at_Site = factor(accident_data$Special_Conditions_at_Site)
  accident_data$Police_Force = factor(accident_data$Police_Force)
  #str(accident_data)

  vehicle_data$Age_Band_of_Driver = factor(vehicle_data$Age_Band_of_Driver,order = "TRUE", levels = c( "Data missing or out of range",
                                                                                             "0 - 5", "6 - 10", "11 - 15", "16 - 20",
                                                                                             "21 - 25", "26 - 35", "36 - 45", 
                                                                                             "46 - 55","56 - 65", "66 - 75", "Over 75"))
  vehicle_data$Driver_Home_Area_Type = factor(vehicle_data$Driver_Home_Area_Type)
  vehicle_data$Propulsion_Code = factor(vehicle_data$Propulsion_Code)
  vehicle_data$Sex_of_Driver = factor(vehicle_data$Sex_of_Driver)
  vehicle_data$Skidding_and_Overturning = factor(vehicle_data$Skidding_and_Overturning)
  vehicle_data$Vehicle_Manoeuvre = factor(vehicle_data$Vehicle_Manoeuvre)
  vehicle_data$X1st_Point_of_Impact = factor(vehicle_data$X1st_Point_of_Impact)
  vehicle_data$make = factor(vehicle_data$make)
  vehicle_data$Vehicle_Leaving_Carriageway = factor(vehicle_data$Vehicle_Leaving_Carriageway)
  vehicle_data$Towing_and_Articulation = factor(vehicle_data$Towing_and_Articulation)
  #str(vehicle_data)


all_the_data <- inner_join(
  accident_data[which(!is.na(accident_data$Accident_Index)),],
  vehicle_data[which(!is.na(vehicle_data$Accident_Index)),])

myData <- all_the_data

hrs <- hour(myData$Time)
hrs <- as.numeric(hrs)

eve <- c(16:20)
morn <- c(6:11)
after <- c(12:15)
lnight <- c(21:23)
hnight <- c(0:5)
val_timings <- c("16 - 20","6 - 11","0 - 5","12 - 15","21 - 23")

myData = myData%>%
  mutate(timing = case_when(
    as.numeric(hour(myData$Time)) %in% eve ~ "16 - 20",
    as.numeric(hour(myData$Time)) %in% morn ~ "6 - 11",
    as.numeric(hour(myData$Time)) %in% hnight ~ "0 - 5",
    as.numeric(hour(myData$Time)) %in% lnight ~ "21 - 23",
    as.numeric(hour(myData$Time)) %in% after ~ "12 - 15"
  ))

myData$timing = factor(myData$timing , order = TRUE, levels = c("0 - 5","6 - 11","12 - 15","16 - 20","21 - 23"))


```

```{r}

DMOR = "Data missing or out of range"
void_weather = c("(Other)", "Other", "Unknown")
void_common = c("None", "Data missing or out of range","None","Other","NA","Unknown","(Other)","Unclassified","Not known")
void_road = c("Unknown")
void_froad = c("Unclassified")

```

```{r}
plot_missing(accident_data)
accident_data["2nd_Road_Class"] = NULL
accident_data["LSOA_of_Accident_Location"] = NULL

```


```{r}
add.alpha <- function(COLORS, ALPHA){
 if(missing(ALPHA)) stop("provide a value for alpha between 0 and 1")
 RGB <- col2rgb(COLORS, alpha=TRUE)
 RGB[4,] <- round(RGB[4,]*ALPHA)
 NEW.COLORS <- rgb(RGB[1,], RGB[2,], RGB[3,], RGB[4,], maxColorValue = 255)
 return(NEW.COLORS)
}

```

```{r}
KDPL <- function(nos){
  ryedale_data <- accident_data[accident_data$Local_Authority_.District. == district,]
  w1 <- c(0)
  ryedale_data <- cbind(ryedale,w1)
  #ryedale_data$w1 <- NA
  ryedale_data[ryedale_data$Accident_Severity == "Fatal", "w1"] <- 3
  ryedale_data[ryedale_data$Accident_Severity == "Serious", "w1"] <- 2
  ryedale_data[ryedale_data$Accident_Severity == "Slight", "w1"] <- 1
  f1 <- kde2d(ryedale_data$Latitude, ryedale_data$Longitude, n = nos)
  w1_f2 <- kde2d.weighted(ryedale_data$Latitude, ryedale_data$Longitude, n = nos, w = ryedale_data$w1)
  pal <- rainbow(20)
  COLORS <- add.alpha(pal, 1)
  par(pty = "s", mfrow = c(1, 2))
  image(f1, col = COLORS)
  image(w1_f2, col = COLORS)
  
  CL <- contourLines(w1_f2$y , w1_f2$x , w1_f2$z)
  
  ## EXTRACT CONTOUR LINE LEVELS
  LEVS <- as.factor(sapply(CL, `[[`, "level"))
  NLEV <- length(levels(LEVS))
  
  ## CONVERT CONTOUR LINES TO POLYGONS
  pgons <- lapply(1:length(CL), function(i)
      Polygons(list(Polygon(cbind(CL[[i]]$x, CL[[i]]$y))), ID=i))
  spgons = SpatialPolygons(pgons)
  
  ## Leaflet map with polygons
  leaflet(spgons) %>% addTiles() %>% 
      addPolygons(color = heat.colors(NLEV, NULL)[LEVS])
  #return (w1_f2)
}

```




```{r}
district = accident_data$Local_Authority_.District.[1]
system.time(KDPL(1000))

```




```{r}

glasgow_city <- myData%>%
  filter(Local_Authority_.District. == "Glasgow City")

ryedale <- myData%>%
  filter(Local_Authority_.District. == "Ryedale")

city_of_london <- myData%>%
  filter(Local_Authority_.District. == "City of London")


```

```{r}
validGender <- c("Male","Female")
what1 <- c("Accident_Index","Accident_Severity")
what2 <- c("Accident_Index","Sex_of_Driver","Age_Band_of_Driver")

severityData <- subset(glasgow_city,select = what1)
genderAge <- subset(glasgow_city,select = what2)%>%
              filter(Sex_of_Driver %in% validGender & Age_Band_of_Driver != DMOR)

plotData <- inner_join(severityData,genderAge)

plt <- ggplot(plotData,aes(x = Age_Band_of_Driver,fill = Accident_Severity))+geom_bar()+facet_wrap(~Sex_of_Driver)
plt <- plt + labs(title = "Accident comparison amongst the genders for Glasgow City")
plt

```

```{r}


what1 <- c("Accident_Index","Accident_Severity")
what2 <- c("Accident_Index","Sex_of_Driver","Age_Band_of_Driver")

severityData <- subset(glasgow_city,select = what1)

genderData <- subset(glasgow_city,select = c("Accident_Index","Sex_of_Driver"))%>%
  filter(Sex_of_Driver %in% validGender)

plotData <- inner_join(severityData,genderData)

plt <- ggplot(plotData,aes(x = Accident_Severity))+geom_bar()
plt <- plt + labs(title = "Accident comparison amongst the genders")
plt

```


```{r}

glasgow_city%>%
  filter(!is.na(Year))%>%
  group_by(Year)%>%
  summarise(accidents = n())%>%
  ggplot(.,aes(x = Year,y = accidents,color = Year))+
  geom_line()+geom_point()+labs(title = "Glasgow City : Accidents over the years")

xd <- glasgow_city%>%
  filter(!is.na(Year))%>%
  group_by(Year)%>%
  summarise(accidents = n())
xd

```

```{r}
nac <- myData

nac <- nac%>%
  filter(!is.na(timing) & !(Sex_of_Driver %in% void_common))


what1 <- c("Accident_Index","Sex_of_Driver")
what2 <- c("Accident_Index","timing")
toUse <- subset(nac,select = c("Accident_Index","Sex_of_Driver","timing","Year") )

pl2 <- toUse%>%
  group_by(timing)%>%
  ggplot(.,aes(x=timing,fill = timing)) +
  theme_bw()+
  facet_wrap(~Sex_of_Driver)+
  geom_bar()+labs(title = "Comparision of accidents at different time-of-day and the genders")

pl2

```

```{r}

KDEP <- function(year){
 
  dist_data <- myData[myData$Local_Authority_.District. == district & myData$Year == year,]
  dist_data$w1 <- NA
  dist_data[dist_data$Accident_Severity == "Fatal", "w1"] <- 3
  dist_data[dist_data$Accident_Severity == "Serious", "w1"] <- 2
  dist_data[dist_data$Accident_Severity == "Slight", "w1"] <- 1
  f1 <- kde2d(dist_data$Latitude, dist_data$Longitude, n = 1000)
  w1_f2 <- kde2d.weighted(dist_data$Latitude, dist_data$Longitude, n = 1000, w = dist_data$w1)
  pal <- rainbow(20)
  COLORS <- add.alpha(pal, 1)
  par(pty = "s", mfrow = c(1, 2))
  image(f1, col = COLORS)
  image(w1_f2, col = COLORS)
  
  CL <- contourLines(w1_f2$y , w1_f2$x , w1_f2$z)
  
  ## EXTRACT CONTOUR LINE LEVELS
  LEVS <- as.factor(sapply(CL, `[[`, "level"))
  NLEV <- length(levels(LEVS))
  
  ## CONVERT CONTOUR LINES TO POLYGONS
  pgons <- lapply(1:length(CL), function(i)
      Polygons(list(Polygon(cbind(CL[[i]]$x, CL[[i]]$y))), ID=i))
  spgons = SpatialPolygons(pgons)
  
  ## Leaflet map with polygons
  xx <- leaflet(spgons) %>% addTiles() %>% 
      addPolygons(color = heat.colors(NLEV, NULL)[LEVS])
  print(xx)
  #return (w1_f2)

}

 
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}
district = "Glasgow City"
KDEP(2005)
KDEP(2006)
KDEP(2007)
KDEP(2008)
KDEP(2009)
KDEP(2010)
KDEP(2011)
KDEP(2012)
```
```{r}

KDEP(2005)

```

```{r}
KDEP(2006)
```

```{r}

KDEP(2007)

```

```{r}

KDEP(2008)

```


```{r}
KDEP(2009)

```

```{r}

KDEP(2010)

```

```{r}

KDEP(2011)

```

```{r}

KDEP(2012)

```

```{r}
KDEP(2013)

```

```{r}

KDEP(2014)

```

```{r}

KDEP(2015)


```

```{r}

KDEP(2016)

```


```{r}





```

```{r}

```

